apiVersion: v1
kind: Service
metadata:
  name: challenge-persist-service
  labels:
    app: challenge-persist
spec:
  type: NodePort
  ports:
    - name: rest
      port: 80
      protocol: TCP
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-persist
  labels:
    app: ice-challenge-persiet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ice-challenge-persiet
  template:
    metadata:
      labels:
        app: ice-challenge-persist
    spec:
      containers:
      - name: ice-challenge-persiet
        image: registry.gitlab.com/channelit/cit-challenge-persist
        ports:
        - containerPort: 8080